export const bandSetListsCopy = {
  title: 'Set lists',
  eyebrow: 'Band show flow',
  empty: 'No set lists yet.',
  createTitle: 'Create set list',
  createButton: 'Create set list',
  nameLabel: 'Name',
  descriptionLabel: 'Description',
  notesLabel: 'Notes',
  songsLabel: 'Songs (comma-separated IDs for now)',
  activate: 'Activate',
  deactivate: 'Deactivate',
  copy: 'Copy',
  delete: 'Delete',
  confirmDeleteTitle: 'Delete this set list?',
  confirmDeleteBody: 'Deleting a set list never removes songs. This action only removes the saved order.',
  confirmDeleteButton: 'Delete set list',
  cancelDeleteButton: 'Cancel',
  activeBadge: 'Active',
  inactiveBadge: 'Inactive',
  activeOnlyNote: 'Only one set list can be active at a time.',
  useSetListNote: 'Use the active set list in the show config when available.',
} as const
