export const bandDashboardViewCopy = {
  operations: {
    showControls: 'Show controls',
    operationsEyebrow: 'Operations',
    showNameLabel: 'Show name',
    descriptionLabel: 'Description',
    showSettings: 'Show settings',
    showDurationLabel: 'Show duration (minutes)',
    bufferLabel: 'Buffer between songs (minutes)',
    songSourceLabel: 'Song source',
    uploadedSongList: 'Uploaded song list',
    tidalPlaylist: 'Tidal playlist',
    startShow: 'Start show',
    saveSettings: 'Save settings',
    openSongLibrary: 'Open song library',
    signupStatus: {
      active: (capacity: number) => `Signups are open. Estimated signup capacity: ${capacity} songs for this set.`,
      paused: 'Signups are paused by the band.',
      ended: 'This show has ended and singer signups are closed.',
    },
  },
  queue: {
    title: 'Queue management',
    queueEyebrow: 'Realtime control',
    liveQueue: 'Live queue',
    history: 'History',
    addBandMember: 'Add band member/admin',
    membersAndAdmins: 'Members & admins',
    noBandMembers: 'No band members yet.',
    noQueue: 'No queue items yet.',
    showSongTitle: 'Song title',
    artistLabel: 'Artist',
    durationLabel: 'Duration',
  },
  singer: {
    title: 'Singer Sign-up',
    signUp: 'Sign-up',
    login: 'Login',
    singerDetails: 'Singer details',
    nowPlaying: 'Now Playing',
    pickASong: 'Pick a song to load lyrics.',
  },
} as const
