export const bandDashboardViewCopy = {
  operations: {
    showControls: 'Show controls',
    operationsEyebrow: 'Operations',
    showNameLabel: 'Show name',
    descriptionLabel: 'Description',
    showSettings: 'Show settings',
    showDurationLabel: 'Show duration (minutes)',
    bufferLabel: 'Buffer between songs (minutes)',
    modeLabel: 'Show mode',
    karaokeMode: 'Karaoke',
    requestsMode: 'Requests',
    songSourceLabel: 'Song source',
    requestSourceLabel: 'Request source',
    uploadedSongList: 'Uploaded songs',
    tidalPlaylist: 'Tidal Playlist',
    tidalCatalog: 'Tidal Catalog',
    setList: 'Set list',
    tidalPlaylistUrlLabel: 'Playlist URL',
    tidalPlaylistNote: 'Singers will browse the band’s imported Tidal playlist instead of the live catalog.',
    requestSourceNote: 'Requests will use this source while the show is in Requests mode.',
    tidalUnavailableNote: 'Connect Tidal before selecting the live catalog for requests.',
    activeSetListLabel: 'Active set list',
    activeSetListNote: 'Uses the band’s currently active set list.',
    noActiveSetList: 'Activate a set list to use set list mode.',
    startShow: 'Start show',
    pauseSignups: 'Pause signups',
    resumeSignups: 'Resume signups',
    undoPause: 'Undo pause',
    endShow: 'End show',
    saveSettings: 'Save settings',
    openSongLibrary: 'Open song library',
    signupStatus: {
      active: (capacity: number) => `Signups are open. Estimated signup capacity: ${capacity} songs for this set.`,
      paused: 'Signups are paused by the band.',
      ended: 'This show has ended and singer signups are closed.',
    },
  },
  queue: {
    title: 'Queue management',
    eyebrow: 'Queue admin',
    positionPrefix: 'Position',
    played: 'Played',
    remove: 'Remove',
    moveUp: 'Move up',
    moveDown: 'Move down',
    empty: 'No queue items yet. Singer requests will show up here automatically.',
    historyTitle: 'History',
    historySubtitle: '(played and cancelled songs)',
    historyEmpty: 'Played and cancelled songs will appear here.',
  },
  profile: {
    title: 'Band profile',
    eyebrow: 'Public links',
    messageTitle: 'Custom message',
    socialsTitle: 'Social links',
    tipsTitle: 'Tip links',
    noMessage: 'No custom band message yet.',
  },
  signupLink: {
    title: 'Singer signup link',
    eyebrow: 'Shareable public flow',
    publicUrl: 'Public URL',
    qrAlt: 'Singer signup QR code',
    qrPrompt: 'Scan this QR code to open the singer sign-up page for this band.',
    empty: 'A public link will appear once the band has a profile and active show.',
  },
  singer: {
    title: 'Singer Sign-up',
    signUp: 'Sign-up',
    login: 'Login',
    singerDetails: 'Singer details',
    nowPlaying: 'Now Playing',
    pickASong: 'Pick a song to load lyrics.',
  },
} as const
