export const bandSetListsCopy = {
  title: 'Set lists',
  eyebrow: 'Band show flow',
  empty: 'No set lists yet.',
  addToSetList: 'Add to set list',
  addToSetListTitle: 'Add song to a set list',
  addToExistingSetList: 'Add to existing set list',
  appendSongButton: 'Add song',
  appendSongNote: 'This will add the song without removing anything already in the set list.',
  createNewSetListTitle: 'Create a new set list with this song',
  createWithSongButton: 'Create set list',
  createWithSongNote: 'Create the set list and seed it with this song.',
  createTitle: 'Create set list',
  createButton: 'Create set list',
  editButton: 'Edit',
  saveButton: 'Save set list',
  nameLabel: 'Name',
  descriptionLabel: 'Description',
  notesLabel: 'Notes',
  selectSetListLabel: 'Select a set list',
  setListPlaceholder: 'Choose a set list',
  noSetListsYet: 'No set lists yet.',
  moveUp: 'Up',
  moveDown: 'Down',
  removeSong: 'Remove',
  songsLabel: 'Songs (comma or newline-separated IDs)',
  songsHelper: 'Blank entries are ignored. Duplicate IDs are removed.',
  activate: 'Activate',
  deactivate: 'Deactivate',
  copy: 'Copy',
  delete: 'Delete',
  confirmDeleteTitle: 'Delete this set list?',
  confirmDeleteBody: 'Deleting a set list never removes songs. This action only removes the saved order and set-list metadata.',
  confirmDeleteButton: 'Delete set list',
  cancelDeleteButton: 'Cancel',
  activeBadge: 'Active',
  inactiveBadge: 'Inactive',
  activeOnlyNote: 'Only one set list can be active at a time.',
  useSetListNote: 'Use the active set list in the show config when available.',
  emptySongs: 'No songs in this set list yet.',
  songCountLabel: (count: number) => `${count} song${count === 1 ? '' : 's'}`,
} as const
