export const tidalSearchPanelCopy = {
  title: 'Pick a Song',
  importedPlaylist: 'Imported Tidal playlist available.',
  catalogMode: 'Searching the live Tidal catalog.',
  placeholder: 'Search the band song list',
  catalogPlaceholder: 'Search the Tidal catalog',
  searching: 'Searching',
  queueing: 'Queueing…',
  queueSong: 'Queue song',
  noMatches: 'No matches yet.',
  unableToAdd: 'Unable to add song request.',
  unableToSearch: 'Unable to search songs.',
  retry: 'Retry',
  readyEyebrow: 'Ready to rock?',
  readyTitle: 'Are you ready to rock?',
  queueMessage: (title: string) => `Queued ${title}.`,
} as const
