export const adminCopy = {
  platformControl: 'Platform control',
  dashboardTitle: 'StageSync Admin',
  dashboardDescription: 'Manage bands, users, and system analytics from one place.',
  login: {
    title: 'Admin login',
    description: 'Use your admin username and password to access system controls.',
    pageTitle: 'StageSync Admin Login',
    pageDescription: 'Admins sign in here with a username and password to manage bands, users, and analytics.',
    submitLabel: 'Sign in',
    successMessage: 'Admin login successful.',
    switchTitle: 'Switch to an admin account',
    switchMessage: 'You\'re currently signed in as a singer. Use an admin username and password to access the admin dashboard.',
  },
  backToAdmin: 'Back to admin',
  logoutLabel: 'Log out',
  cards: {
    bands: { title: 'Manage bands', description: 'CRUD bands and members.' },
    users: { title: 'User management', description: 'CRUD singers, band members, and admins.' },
    analytics: { title: 'System analytics', description: 'Track usage, queue volume, and show health.' },
    bandProfiles: { title: 'Band profiles', description: 'Modify public band profile records.' },
  },
  bandProfilesPage: {
    title: 'Band profiles',
    description: 'Create and edit band profile records.',
    backToAdmin: 'Back to admin',
    createTitle: 'Create band profile',
    profileLabel: 'Profile',
    selectProfile: 'Select profile',
    bandNameLabel: 'Band name',
    customMessageLabel: 'Custom message',
    createButton: 'Create profile',
    profileIdLabel: 'Profile ID',
    edit: 'Edit',
    saveChanges: 'Save changes',
    delete: 'Delete',
  },
  bandsPage: {
    title: 'Manage bands',
    description: 'Create, edit, and delete band login accounts.',
    searchPlaceholder: 'Search bands or users',
    liveTitle: 'Live bands',
    liveDescription: 'Search bands, edit profile details, and manage band admins/members.',
    createTitle: 'Create band',
    createModeLabel: 'Create mode',
    createModeExisting: 'Associate existing profile',
    createModeNewUser: 'Create new band admin user',
    bandRoleLabel: 'Band role',
    bandRoleAdmin: 'admin',
    bandRoleMember: 'member',
    bandNameLabel: 'Band name',
    existingProfileLabel: 'Existing profile username',
    firstNameLabel: 'First name',
    lastNameLabel: 'Last name',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    usernameLabel: 'Username',
    customMessageLabel: 'Custom message',
    websiteLabel: 'Website',
    facebookLabel: 'Facebook',
    instagramLabel: 'Instagram',
    tiktokLabel: 'TikTok',
    paypalLabel: 'PayPal',
    venmoLabel: 'Venmo',
    cashappLabel: 'Cash App',
    createButton: 'Create band',
    backToAdmin: 'Back to admin',
    noBands: 'No bands yet.',
    noCustomMessage: 'No custom band message yet.',
    bandIdLabel: 'Band ID',
    bandNameLabel: 'Band name',
    membersTitle: 'Members & admins',
    addMemberTitle: 'Add band member/admin',
    profileSearchPlaceholder: 'Search existing profile username',
    searchButton: 'Search',
    previous: 'Previous',
    next: 'Next',
    edit: 'Edit',
    saveChanges: 'Save changes',
    delete: 'Delete',
    remove: 'Remove',
    attachToBand: 'Attach to band',
    bandMembersEmpty: 'No band members yet.',
    noCustomMessage: 'No custom band message yet.',
    currentAdmin: 'Current admin',
    member: 'member',
  },
  usersPage: {
    title: 'User management',
    description: 'Search users, filter by role, page through the full dataset, and manage band assignments.',
    liveTitle: 'Live users',
    liveDescription: 'Create singers, band admins, and band members. Search is full-dataset.',
    searchPlaceholder: 'Search users',
    searchButton: 'Search',
    allUsers: 'All users',
    singers: 'Singers',
    bandMembers: 'Band members',
    admins: 'Admins',
    createModeLabel: 'Create mode',
    createModeNewUser: 'Create new auth user',
    createModeExistingProfile: 'Use existing profile',
    roleLabel: 'Role',
    profileLookupLabel: 'Profile username or existing profile',
    usernameLabel: 'Username',
    displayNameLabel: 'Display name',
    firstNameLabel: 'First name',
    lastNameLabel: 'Last name',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    bandLabel: 'Band',
    bandRoleLabel: 'Band role',
    saveUser: 'Save user',
    edit: 'Edit',
    saveChanges: 'Save changes',
    remove: 'Remove',
    delete: 'Delete',
    previous: 'Previous',
    next: 'Next',
    bandMemberships: 'Band memberships',
    noBandMemberships: 'No band memberships yet.',
    activeBand: 'Active band',
    addBand: 'Add band',
    bandRoleMember: 'member',
    bandRoleAdmin: 'admin',
  },
  analyticsPage: {
    title: 'System analytics',
    description: 'Visibility into shows, singers, and track utilization.',
    recentShowsTitle: 'Recent shows',
    activeLabel: 'active',
    endedLabel: 'ended',
    signupsOn: 'signups on',
    signupsOff: 'signups off',
    metrics: {
      bandShows: 'Band-shows',
      activeShow: 'Active Show',
      singerCount: 'Singer count',
      tracksPlayed: 'Tracks played',
    },
  },
} as const
