export const bandCopy = {
  dashboard: {
    eyebrow: 'Band control',
    title: 'StageSync Band Dashboard',
    description: 'Manage the current show, queue, and band profile without exposing those controls to singers.',
    links: {
      account: 'Account',
      members: 'Members',
      songs: 'Song library',
    },
  },
  bandPortal: 'Band portal',
  login: {
    title: 'Band login',
    description: 'Use your band username and password to access show controls.',
    submitLabel: 'Sign in',
    successMessage: 'Band login successful.',
    accountTitle: 'Band account',
    membersTitle: 'Band members',
    songsTitle: 'Song library',
    accountDescription: 'Edit your band profile and login credentials.',
    membersDescription: (bandName: string) => `Create, edit, delete, and promote members for ${bandName}.`,
    songsDescription: 'Manage the band’s song list, import from CSV, Google Sheets, or Tidal, and keep the singer picker fast.',
    bandAdminTitle: 'Edit Band Admin',
    bandAdminDescription: 'Use your band username and password to access show controls.',
    bandAdminSuccess: 'Band admin updated successfully.',
    accessDenied: 'Band admin access required.',
    editBandProfile: 'Edit Band Profile',
    editBandAdmin: 'Edit Band Admin',
    createMember: 'Create member',
    backToDashboard: 'Back to band dashboard',
    loginRequired: 'Band login required.',
  },
  bandLogin: {
    pageTitle: 'StageSync Band Login',
    pageDescription: 'Band members sign in here with a username and password to manage the show, queue, and profile settings.',
    switchTitle: 'Switch to a band account',
    switchMessage: 'You\'re currently signed in as a singer. Use a band email to get the band dashboard.',
  },
} as const
