export const bandCopy = {
  dashboard: {
    eyebrow: 'Band control',
    title: 'StageSync Band Dashboard',
    description: 'Manage the current show, queue, and band profile without exposing those controls to singers.',
    links: {
      account: 'Account',
      members: 'Members',
      songs: 'Song library',
    },
  },
  bandPortal: 'Band portal',
  login: {
    title: 'Band login',
    description: 'Use your band username and password to access show controls.',
    submitLabel: 'Sign in',
    successMessage: 'Band login successful.',
    accountTitle: 'Band account',
    membersTitle: 'Band members',
    songsTitle: 'Song library',
    accountDescription: 'Edit your band profile and login credentials.',
    membersDescription: (bandName: string) => `Create, edit, delete, and promote members for ${bandName}.`,
    songsDescription: 'Manage the band’s song list, import from CSV, Google Sheets, or Tidal, and keep the singer picker fast.',
    bandAdminTitle: 'Edit Band Admin',
    bandAdminDescription: 'Use your band username and password to access show controls.',
    bandAdminSuccess: 'Band admin updated successfully.',
    accessDenied: 'Band admin access required.',
    editBandProfile: 'Edit Band Profile',
    editBandAdmin: 'Edit Band Admin',
    createMember: 'Create member',
    backToDashboard: 'Back to band dashboard',
    loginRequired: 'Band login required.',
  },
  bandLogin: {
    pageTitle: 'StageSync Band Login',
    pageDescription: 'Band members sign in here with a username and password to manage the show, queue, and profile settings.',
    switchTitle: 'Switch to a band account',
    switchMessage: 'You\'re currently signed in as a singer. Use a band email to get the band dashboard.',
  },
  songsPage: {
    mainDescription: 'Manage the band’s song list, import from CSV, Google Sheets, or Tidal, and keep the singer picker fast.',
    signedInAs: 'Signed in as',
    noBandSelected: 'No active band selected.',
    importSongsTitle: 'Import songs',
    importSongsDescription: 'Every import lands in the same songs table, so singers can search one library no matter where the list came from.',
    importQueuedTitle: 'Tidal import queued',
    importQueuedProcessing: 'The background job is processing the playlist now.',
    importQueuedProgress: 'Progress',
    importQueuedErrorPrefix: 'Error:',
    uploadCsvTitle: 'Upload CSV',
    csvColumns: 'Columns: Artist, Song Title, Duration.',
    csvFileLabel: 'CSV file',
    importCsvButton: 'Import CSV',
    importSheetTitle: 'Import Google Sheet',
    sheetDescription: 'Paste a public sheet URL that has Artist, Song Title, Duration.',
    sheetUrlLabel: 'Sheet URL',
    importSheetButton: 'Import Sheet',
    importTidalTitle: 'Import Tidal Playlist',
    tidalDescription: 'Paste a public Tidal playlist URL. The app will fetch Artist, Song Title, and Duration through the Tidal API flow.',
    playlistUrlLabel: 'Playlist URL',
    importPlaylistButton: 'Import Playlist',
    addSongTitle: 'Add a song',
    addSongDescription: 'Manually create a song entry when it’s not coming from an import.',
    songTitleLabel: 'Song title',
    artistLabel: 'Artist',
    durationLabel: 'Duration (ms)',
    saveSongButton: 'Save song',
    songListTitle: 'Song list',
    activeSongsSuffix: 'active songs in the library.',
    manageSetListsButton: 'Manage set lists',
    searchPlaceholder: 'Search songs',
    searchButton: 'Search',
    rowArtistLabel: 'Artist',
    rowSongTitleLabel: 'Song title',
    rowDurationLabel: 'Duration',
    editButton: 'Edit',
    saveButton: 'Save',
    archiveButton: 'Archive',
    deleteAllSongsButton: 'Delete all songs',
    deleteAllSongsConfirmTitle: 'Delete all songs in this band song list?',
    deleteAllSongsConfirmBody: 'This will archive every current song for the active band. Imported songs and Tidal behavior stay intact for future imports, but the current song list will be cleared.',
    deleteAllSongsArchivedMessage: 'All songs in this band were archived.',
    noSongs: 'No songs yet.',
    pageLabel: 'Page',
    previousButton: 'Previous',
    nextButton: 'Next',
    sourceUploaded: 'uploaded',
    sourceRefPrefix: 'Ref:',
  },
  accountPage: {
    saveAccountButton: 'Save account',
    bandNameLabel: 'Band name',
    saveBandProfileButton: 'Save band profile',
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    logoUrlLabel: 'Logo URL',
    websiteUrlLabel: 'Website',
    facebookUrlLabel: 'Facebook',
    instagramUrlLabel: 'Instagram',
    tiktokUrlLabel: 'TikTok',
    paypalUrlLabel: 'PayPal',
    venmoUrlLabel: 'Venmo',
    cashappUrlLabel: 'Cash App',
    customMessageLabel: 'Custom message',
    tidalCredentialsLabel: 'Tidal credentials',
    tidalClientIdLabel: 'Tidal developer key',
    tidalClientSecretLabel: 'Tidal secret',
    tidalCredentialsNote: 'Used when a show is set to Tidal Catalog. Leave the secret blank to keep the current value.',
    bandFallbackName: 'Band',
  },
  membersPage: {
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    roleLabel: 'Role',
    bandLabel: 'Band',
    memberRole: 'Member',
    adminRole: 'Band admin',
    currentAdmin: 'Current admin',
    editButton: 'Edit',
    saveMemberButton: 'Save member',
    deleteButton: 'Delete',
    leaveBlankPlaceholder: 'Leave blank to keep current password',
    createAndDeleteDescription: 'Create, edit, and delete members',
  },
} as const
