export const sharedCopy = {
  brandName: 'StageSync',
  signIn: 'Sign in',
  logOut: 'Log out',
  close: 'Close',
  save: 'Save',
  edit: 'Edit',
  delete: 'Delete',
  search: 'Search',
  loading: 'Loading…',
  errorGeneric: 'Something went wrong.',
  loggedInAs: 'Logged in as',
  guestSinger: 'Guest singer',
  unknownArtist: 'Unknown artist',
  unknownSong: 'Unknown song',
  queuedStatus: 'queued',
  noActiveBandSelected: 'No active band selected.',
} as const
